---
# Source: promtail/templates/clusterrolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-name-promtail-clusterrolebinding
  labels:
    app: promtail
    chart: promtail-0.12.2
    release: release-name
    heritage: Tiller
subjects:
  - kind: ServiceAccount
    name: release-name-promtail
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: release-name-promtail-clusterrole
  apiGroup: rbac.authorization.k8s.io
