---
# Source: promtail/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: promtail
    chart: promtail-0.12.2
    heritage: Tiller
    release: release-name
  name: release-name-promtail
  namespace: kube-system

