apiVersion: v1
kind: Service
metadata:
  name: test-aws-k8s-master
  labels:
    app: test-aws-k8s-master
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: test-aws-k8s-master
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-wordpress-test-aws-k8s-master
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.org/client-max-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "kops.example.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: test-aws-k8s-master
          servicePort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-aws-k8s-master
  labels:
    app: test-aws-k8s-master
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: test-aws-k8s-master
      tier: frontend
  template:
    metadata:
      labels:
        app: test-aws-k8s-master
        tier: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/instancegroup
                operator: In
                values:
                - nodes
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - test-aws-k8s-master
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: php-fpm
        image: easyengine/k8s-php:v1.0.0
        resources:
          limits:
            cpu: "0.2"
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 64Mi
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
            - name: Host
              value: "kops.example.com"
          initialDelaySeconds: 0
          periodSeconds: 1
          successThreshold: 3
          timeoutSeconds: 60
        # volumeMounts:
        # - name: wp-config-vol
        #   mountPath: "/tmp/wp-config"
        #   readOnly: true
        ports:
        - containerPort: 9000
        env:
        - name: DB_NAME
          value: "test-aws-k8s"
        - name: DB_HOST
          value: "wordpress-mysql.mariadb.svc.cluster.local"
        - name: WP_USER
          value: "admin"
        - name: WP_PASS
          value: "password"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "Ljdbeh779302yhekLSJDB"
        - name: SITE_NAME
          value: "kops.example.com"
        - name: SITE_TITLE
          value: "Simple WordPress"
        - name: IS_REDIS
          value: "redis"
        - name: REDIS_HOST
          value: "wordpress-redis.redis.svc.cluster.local"
        - name: MU
          value: "none"
        - name: UPDATE_RUN
          value: "setup"
      - name: nginx
        image: easyengine/k8s-nginx:v1.0.0
        resources:
          limits:
            cpu: "0.2"
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 64Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: SITE_NAME
          value: kops.example.com
        - name: MU
          value: "none"
        - name: IS_REDIS
          value: "redis"
        - name: REDIS_HOST
          value: "wordpress-redis.redis.svc.cluster.local"
        # volumeMounts:
        # - name: wp-config-vol
        #   mountPath: "/tmp/wp-config"
        #   readOnly: true

      # - name: newrelic-daemon
      #   image: mrrobot47/newrelic-daemon:v1.0.3
      #   imagePullPolicy: Always
      #   ports:
      #   - containerPort: 31111

      terminationGracePeriodSeconds: 60
      # volumes:
      # - name: wp-config-vol
      #   secret:
      #     secretName: wp-config
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: test-aws-k8s-master
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-aws-k8s-master
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 20
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 20

