apiVersion: v1
kind: Service
metadata:
  name: blackbox
  labels:
    name: blackbox
  annotations:
    prometheus.io/probe: "true"
spec:
  ports:
    - port: 80
      targetPort: blackbox
      protocol: TCP
  selector:
    rabbitmq-blackbox: "true"