apiVersion: v1
kind: ReplicationController
metadata:
  name: blackbox
spec:
  replicas: 1
  selector:
    app: rabbitmq
    rabbitmq-blackbox: "true"
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
        rabbitmq-blackbox: "true"
    spec:
      containers:
      - image: prom/blackbox-exporter
        imagePullPolicy: Always
        name: rabbitmq-blackbox
        ports:
        - containerPort: 9115
          name: blackbox
      