apiVersion: v1
kind: Service
metadata:
  name: release-name-loki
  namespace: kube-system
  labels:
    app: loki
    chart: loki-0.14.3
    release: release-name
    heritage: Tiller
  annotations:
    {}
    
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: loki
    release: release-name

